#!/bin/sh /etc/rc.common

START=99

start () {
    ResultPath='/tmp/dnsmasq.d/domains.lst'

    DOMAINS=https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-dnsmasq-nfset.lst
    UNIQORNS=https://raw.githubusercontent.com/Anybes28/ButterfliesAndUnicorns/main/Uniqorns.lst

    echo 'start uniqorns'

    count=0
    while true; do
        if curl -m 3 github.com; then
            curl -f $DOMAINS --output $ResultPath
            echo "" >> $ResultPath
            curl -f $UNIQORNS >> $ResultPath

            echo "uniqorns complete and exist"
            break
        else
            echo "GitHub is not available. Check the internet availability [$count]"
            count=$((count+1))
        fi
    done

    if dnsmasq --conf-file=/tmp/dnsmasq.d/domains.lst --test 2>&1 | grep -q "syntax check OK"; then
  