#!/bin/sh /etc/rc.common

START=99

script () {
    DIR=/tmp/lst
    IP=https://raw.githubusercontent.com/Anybes28/ButterfliesAndUnicorns/main/Ip.lst
    MYDOMAINS=https://raw.githubusercontent.com/Anybes28/ButterfliesAndUnicorns/main/Domains.lst
    DOMAINS=https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-dnsmasq-nfset.lst

    download(){
        count=0
        while true; do
            if [ $count -gt 10 ]; then
                echo "Exit by time out"
                exit 1
            fi

            if curl -m 3 github.com; then
                curl -f $2 --output $1
                break
            else
                echo "GitHub is not available. Check the internet availability [$count]"
              :  count=$((count+1))
                sleep 5
            fi
        done
    }

    mkdir -p $DIR

    echo "Run download lists"

    download $DIR/ip.lst $IP

    download $DIR/mydomains.lst $MYDOMAINS

    DNSMASQ_DOMAINS_DIR=/tmp/dnsmasq.d
    download $DNSMASQ_DOMAINS_DIR/domains.lst $DOMAINS
    echo "" >>  $DNSMASQ_DOMAINS_DIR/domains.lst
    sed "s/.*/nftset=\/&\/4#inet#fw4#vpn_domains/" $dir/mydomains.lst >>  $DNSMASQ_DOMAINS_DIR/domains.lst

    echo "Dnsmasq restart"
    /etc/init.d/dnsmasq restart

    echo "Firewall restart"
    /etc/init.d/firewall restart
}

start () {
    script
}

restart () {
    script
}

reload () {
    script
}
